# Generated by Django 4.1.6 on 2023-02-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cylinder',
            field=models.IntegerField(default=0, verbose_name='Cylindré'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=30, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Modèle'),
        ),
        migrations.AlterField(
            model_name='car',
            name='version',
            field=models.CharField(max_length=50, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='car',
            name='years',
            field=models.IntegerField(verbose_name='Année de construction'),
        ),
    ]
