# Generated by Django 4.1.6 on 2023-02-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_cylinder_alter_car_brand_alter_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='cylinder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='years',
            field=models.IntegerField(default=0),
        ),
    ]
